name: compclass
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - numpy>=1.16
  - matplotlib>=3.0
  - pandas>=0.24
  - scipy>=1.2
  - jupyterlab>=0.35
  - uncertainties>=3.0
  - uproot>=3.5
  - plumbum>=1.6.6
  - lmfit>=0.9
